### PR TITLE
Fix iap-promoted-product listener

### LINKED ISSUE #950: Promoted IAP listener not firing in 4.4.2? (working in 4.4.1)
### Version of react-native-iap
4.4.2
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
The 'iap-promoted-product' event listener fires when opening the app using a itms-services:// link.
### Actual behavior
The 'iap-promoted-product' event listener does not fire.
### Tested environment (Emulator? Real Device?)
Real Device. Iphone 7.

I had a working implementation of the promoted IAP workflow that stopped working once I upgraded to the 4.4.2 version. Sounds weird being a minor release, but downgrading solved the issue.

### PR DESCRIPTION
**Pull request by ghsdh3409**
### Summary
* It closes #950 
* This PR fixes `iap-promoted-product` listener by merging `IAPPromotionObserver` and `RNIap`.
* After [v4.4.5](https://github.com/dooboolab/react-native-iap/commit/c50ef1e156dd62c89e629c67caa952b2cd702113#diff-f536a7b99578ee1c2849b920c4f01332), `iap-promoted-product` was not triggered, since transaction observer was not added in the `IAPPromotionObserver`.
* So, In the issue #950, @hyochan proposed to merge `IAPPromotionObserver` to `RNIap` file is iOS to call `addTransactionObserver:self` just once. ([comment](https://github.com/dooboolab/react-native-iap/issues/950#issuecomment-622372069))

### How to review
* Code review
* Device test
  * I tested on the device with IAP promotion test URL.

### CODE REVIEW

File: ios/RNIapIos.h [hunk 1]
```diff
@@ -6,6 +6,8 @@
 {
   SKProductsRequest *productsRequest;
   NSMutableArray *validProducts;
+  SKPayment *promotedPayment;
+  SKProduct *promotedProduct;
```
Comment (ghsdh3409) [inline ios/RNIapIos.h:10]: This is merged from the following code.

https://github.com/dooboolab/react-native-iap/blob/3f103f20c674c091fa69b715102bfc4caac37462/ios/IAPPromotionObserver.m#L4-L5

File: ios/RNIapIos.m [hunk 2]
```diff
@@ -95,12 +92,14 @@ -(void)rejectPromisesForKey:(NSString*)key code:(NSString*)code message:(NSStrin
...
 
-////////////////////////////////////////////////////     _//////////_  // IAPPromotionObserverDelegate
-- (BOOL)shouldAddStorePayment:(SKPayment *)payment forProduct:(SKProduct *)product {
-    if (hasListeners) {
-        [self sendEventWithName:@"iap-promoted-product" body:product.productIdentifier];
-    }
-    return NO;
+- (BOOL)paymentQueue:(SKPaymentQueue *)queue shouldAddStorePayment:(SKPayment *)payment forProduct:(SKProduct *)product {
+  promotedProduct = product;
+  promotedPayment = payment;
```
Comment (ghsdh3409) [inline ios/RNIapIos.m:97]: This code is merged from the following code.

https://github.com/dooboolab/react-native-iap/blob/3f103f20c674c091fa69b715102bfc4caac37462/ios/IAPPromotionObserver.m#L50-L52

**Comment by hyochan** [comment]
Release 4.5.0! @ghsdh3409
